version: '2'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
     - db_data:/var/lib/mysql    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress     
  httpd:
    depends_on:
      - db
    image: apachephp:7.1
    volumes:
      - ./:/var/www/html
      - ./_log:/var/log/apache2
    ports:
      - "80:80"
      - "9000:9000"
    links:
      - db:mysql
  wpcli:
    image: tatemz/wp-cli
    volumes_from:
      - httpd
    links:
      - db:mysql
    entrypoint: wp  
    command: "--info"
  phpma:
    image: phpmyadmin/phpmyadmin
    volumes:
      - sessions:/sessions
    ports:
      - "81:80"
    links:
      - db:mysql
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root       

volumes:
  db_data:
    driver: local
  sessions:
    driver: local    