version: '2'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
     - db_data:/var/lib/mysql    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress     
  httpd:
    depends_on:
      - db
    image: customhttpd:basic
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    links:
      - db:mysql
  wpcli:
    image: tatemz/wp-cli
    volumes_from:
      - httpd
    links:
      - db:mysql
    entrypoint: wp  
    command: "--info"

volumes:
  db_data:
    driver: local